### ISSUE TITLE
How to setup dispatcher without UI

### ISSUE THREAD

**Issue by GomesNayagam** [microcks/microcks-testcontainers-dotnet#65]
Hi @devznsh  I am planning to use this for my dotnet integration test. 

currently the basic thig works with sample mock payload, but how do i setupu dispatcher rule here.

e..g

I have two mock 

1) { UnitNumber: 12345} => Response1

2) {UnitNumber : 4567} => Response2

**Comment by SebastienDegodez** [comment]
Hello, 

If i understand you can use import content artifact.

https://github.com/microcks/microcks-testcontainers-dotnet?tab=readme-ov-file#import-content-in-microcks

To specify a specific response, i like used APIExamples and import with secondary méthodes.

https://microcks.io/documentation/references/examples/


```
[...]
operations:
  'greeting':
    Laurent:
      request:
        body:
          firstname: Laurent
          lastname: Broudoux
      response:
        body:
          greeting: Hello Laurent Broudoux !
    John:
      request:
        body: |-
          {"firstname": "John", "lastname": "Doe"}          
      response:
        body:
          greeting: Hello John Doe !
```
